steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/backend_api_template:$COMMIT_SHA',
        '.'
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend_api_template:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [
        '-c',
        'gcloud run deploy backend_api_template
        --image gcr.io/$PROJECT_ID/backend_api_template:$COMMIT_SHA
        --region us-central1
        --allow-unauthenticated
        --set-env-vars "SECRETS_API_BASE_URL=${_SECRETS_API_BASE_URL},
        SECRETS_API_KEY=${_SECRETS_API_KEY}"
        '
      ]
images:
  - 'gcr.io/$PROJECT_ID/backend_api_template:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
